#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_RESERVATION_SIZE (256)
#define STATE_ACCESS_DELAY_US (500000)  // 500ms
#define MAX_JOB_FILE_NAME_SIZE (256)
#define MAX_SESSION_COUNT (8)

#define S (20) // NUM_SESSIONS

#endif /* CONSTANTS_H */
